### ISSUE TITLE
[TASK] products

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi-2#4]
**Description**
A clear and concise description of the task and who does it.

**Details**
A clear and detailed explanation, with steps, of what you want to happen.

**Parent Issue**
Add any parent issues to this issue

**Child Issues**
Add any child issues to the case here

**Additional context**

**Milestone**
Set the milestone if applicable.

**Comment by franfif** [comment]
- Fixed CRUD operations for Products
- Added decorator to views to ensure login is required
- Used Function-based views

See pull request: #18
